# Day 10: Simulations and the Metropolis Algorithm

#### &#9989; **Write your name here**

In previous assignments, we have made use of computing tools in Python (e.g., numpy arrays and solve_ivp) to turn problems that would normally be unwieldy in an analytic context (i.e., pen and paper) into much more doable process. This allows us to quickly gain insight into what exact solutions to physics problems might look like.

However, the power of computing goes beyond quick and accurate approximations and numerical problem-solving. We can also use computing to create new models that would not be possible at all without computing capabilities like animation and randomization. One such modeling tool is a Monte Carlo simulation. Monte Carlo is a set of simulation algorithms that use probability distributions to model the evolution of a system.

Over the next two days, we will use the [**Metropolis algorithm**](https://en.wikipedia.org/wiki/Metropolis%E2%80%93Hastings_algorithm) (a specific type of Monte Carlo method) to model the evolution of a system of spin-particles. This can give us insight into the behavior of many different materials, most famously ferromagnets.

For today, we will learn the tools needed to create this model in Python. Later, we will combine these tools together to build and visualize a full simulation of a spin system.

---
## Part 1: Metropolis algorithm

Here are the basic steps in the Metropolis Monte Carlo algorithm, and the more specific version you will code today using a 2D lattice of spins.

| Step | Metropolis algorithm | Today's assignment |
|------|----------------------|--------------------|
| **1** | Establish an initial configuration of a system | Establish a random 2D array of spins |
| **2** | Randomly generate a possible change to the system | Randomly choose a spin |
| **3** | Calculate the probability of accepting that change | The probability of flipping that spin is fixed at 50% |
| **4** | Accept or reject the change based on that probability | Flip a coin and decide whether to flip the spin |
| **5** | Go back to step 2 and repeat the algorithm | Go back to step 2 and repeat the algorithm |


&#9989; **Task 1.1:** Group up with some other students. On a large whiteboard, draw a 3x3 grid of spins with a mix of spin-ups and spin-downs. Enact a few iterations of the above algorithm until you feel comfortable explaining the five steps above.

---
## Part 2: Creating a spin system

Creating a spin system is **Step 1** of enacting the Metropolis algorithm.

One function is provided to help you get started with the coding. `init_spins` creates a 2D array of random spins. We use 1 to indicate spin-up, and -1 to indicate spin-down. This is for simplicity when we visualize the spins.

In [10]:
import numpy as np

# init_spins: initialize a random 2D lattice of spins
# L: the side length of the 2D lattice of spins
# output: a 2D array of spins arranged in a square with random values -1 and 1
def init_spins(L):
    lattice = np.ones([L, L], dtype=int)
    rand_cells = np.random.random([L, L]) < 0.5
    lattice[rand_cells] = -1
    return lattice

**&#9989; Task 2.1:** Using the `init_spins` function, create a 10x10 array of spins, and print it out.

In [1]:
# your answer here

**&#9989; Task 2.2:** There is a local variable in the provided function called `rand_cells`, which gets defined as `np.random.random([L, L]) < 0.5`. Use the cell below to **explore what this snippet of code does.** Chat with a peer or instructor to talk through what you think `rand_cells` is doing. Below the code cell, **explain these two lines of code** from `init_spins`:

```
    rand_cells = np.random.random([L, L]) < 0.5
    lattice[rand_cells] = -1
```

In [16]:
# use this cell as needed




**/your answer here/**

#### &#128721; **Stop here and check in with an instructor.**

---
## Part 3: Coding Probability

At this point, we need to use probability to change the system of spins. Probability will help us execute **Steps 2-4** in our enactment of the Metropolis algorithm:

**Step 2:** Randomly choose a spin.  
**Step 3:** The probability of flipping that spin is fixed at 50%.  
**Step 4:** Flip a coin and decide whether to flip the spin.  

In **Step 2**, we need to choose a spin to flip. We can do this by randomly selecting a row and a column, which will specify a random location in our 2D array.

In [123]:
# you can use these arrays to get row and column indices in the next task
rows = np.arange(10)
cols = np.arange(10)

**&#9989; Task 3.1:** Using the `np.random.choice` function, generate a random row and column number (this will be the `i` and `j` that represent the location of a random cell in the spin lattice). Run your code several times to observe the random behavior.

In [ ]:
# your answer here

**&#9989; Task 3.2:** Generate a random pair of row/column indices, and use them to randomly select a spin from the lattice below. **Print out the two indices and the spin value.**

In [73]:
# some code already provided
lattice = init_spins(10)
rows = np.arange(lattice.shape[0])
cols = np.arange(lattice.shape[1])

# your answer here



In **Step 3**, we define our probability of flipping: 0.5. Use the provided variable `p` to represent this probability.

In [75]:
p = 0.5

In **Step 4**, we use a coin-flip to decide whether to flip the spin. 

We can simulate a coin-flip using the `np.random.random` function. This function, when called without input (like `np.random.random()`), randomly generates a decimal between 0 and 1. Half the time, this decimal will be greater than `p`, and half the time it will less. That is our computerized coin-flip!

**&#9989; Task 3.4:** Using `np.random.random`, generate a random decimal between 0 and 1, and print whether it is less than `p`. **Your printed output should be a Boolean `True`/`False` value.** If you re-run your code, you should see the output change sometimes, just like flipping a coin.

*Hint: If you get stuck, go back and re-read your explanation of the code in Task 2.2.*

In [79]:
# your answer here
# begin by executing np.random.random() a few times to see its behavior

np.random.random()

0.8561712075686345

You now have a snippet of code that can be used to decide whether to flip the spin. All that remains in **Step 4** is to flip it! We'll use a small lattice to demonstrate how to do this.

In [94]:
# run this code to get your small lattice of spins
L = 3
spins_small = init_spins(L)

**&#9989; Task 3.5:** Using the `spins_small` lattice, enact **Steps 2-4** of the Metropolis algorithm: randomly choose a spin, flip a coin, and use the coin-flip result to choose whether flip the spin (flipping changes it from 1 to -1, or -1 to 1). **Print the resulting lattice.**

The initial configuration should also be printed at the top of the cell, so you can compare the before/after. When your code works properly, you should be able to run the cell and see two similar spin lattices. Half the time, the systems will be the same. Half the time, one spin will be flipped.

In [96]:
# keep this line of code at the top to compare your result with
print(spins_small)

# your answer here


[[ 1  1  1]
 [ 1 -1 -1]
 [-1  1 -1]]


#### &#128721; **Stop here and check in with an instructor.**

---
## Part 4: Animating a spin system

The last step in our Metropolis algorithm is **Step 5: repeat the algorithm.** This is when we go from flipping just one spin, to modeling the evolution of a spin system over many steps. First, we will learn how to animate, and then we will combine this tool with the spin-flipping you did in Part 3.

Run the cell below and study the code written. If you speed up the animation, it might start to look like [**TV static**](https://en.wikipedia.org/wiki/Noise_(video)) from antenna-based analog TV.

In [106]:
# import plotting and animation functions
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation

# tune settings for the animation window
plt.rcParams["animation.html"] = "jshtml"
plt.rcParams['figure.dpi'] = 60
plt.ioff()
fig, ax = plt.subplots()

# viz_spins creates visualization of the spin lattice
def viz_spins(lattice):
    plt.imshow(lattice, cmap='gray')
    plt.xticks([])
    plt.yticks([])

# initialize spin lattice
latt = init_spins(10)

# animate creates a single frame of the animation
def animate(t):
    plt.cla()
    latt = init_spins(10)
    viz_spins(latt)

# compute and stitch together 100 frames into the animation window
FuncAnimation(fig, animate, frames=100)

**&#9989; Task 4.1:** Based on what you see in the code, discuss with your group and **write an explanation** for why the animation shows the lattice constantly changing from frame to frame like static.

**/your answer here/**

#### &#128721; **Stop here and check in with an instructor.**

**&#9989; Task 4.2:** Rewrite the body of the `animate` function. Your new `animate` function should execute **Steps 2-4** of the Metropolis algorithm, so that the **animation shows spins flipping one at a time between frames**, and around 50% of the frames showing no change, just like the coin flip.

In [110]:
# tune settings for the animation window
plt.rcParams["animation.html"] = "jshtml"
plt.rcParams['figure.dpi'] = 60
plt.ioff()
fig, ax = plt.subplots()

# initialize spin lattice
latt = init_spins(10)

# animate creates a single frame of the animation
def animate(t):
    # we keep plt.cla() -- this clears the plot between frames
    plt.cla()
    # write the rest of the function below
    
    
    

# compute and stitch together 100 frames into the animation window
FuncAnimation(fig, animate, frames=100)

---
## Part 5: New probabilities

In **Step 3**, we quickly set $p=0.5$ as our probability and moved on. But in reality, the behavior of spins can depend on their location in a material. Let's institute a new probability that is slightly more complicated:
- If the spin is located in the **top three rows** of the lattice, and it is currently a **spin-up**, its flipping probability is **0.05**.
- If the spin is located in the **bottom three rows** of the lattice, and it is currently a **spin-down**, its flipping probability is **0.05**.
- Otherwise the spin's flipping probability is **0.8**.

**&#9989; Task 5.1:** How do you expect this new probability to impact the spin system over many steps of the algorithm? **Predict what an animation of this system would look like**, and describe it below.

**/your answer here/**

**&#9989; Task 5.2:** Below, copy your code from Task 4.2. Alter it to institute this new probability.

In [ ]:
# your answer here

**&#9989; Task 5.3:** View the animation and evaluate your prediction from Task 5.1. You may need to increase the frames of the animation to see the long-term behavior of the system.

**/your answer here/**

#### &#128721; **Stop here and check in with an instructor.**